server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9091

  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        createdOut:
          destination: rental.reservationCreated
