server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

spring:
  jpa:
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9091

  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        createdOut:
          destination: rental.reservationCreated
