server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - routes

zuul:
  routes:
    inventory-query:
      stripPrefix: false
      path: /inventories/**
      serviceId: inventory-query

    reservation:
      stripPrefix: false
      path: /reservations/**
      serviceId: reservation
