server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

spring:
  kafka:
    bootstrap-servers: localhost:9091

  cloud:
    stream:
      bindings:
        createdIn:
          destination: rental.reservationCreated
          group: emailer_service_group

        carReservedAtLocationIn:
          destination: rental.carReservedAtLocation
          group: emailer_service_group
