server:
  port: 8082

spring:
  h2:
    console:
      path: /h2
      enabled: true

  kafka:
    bootstrap-servers: localhost:9091

  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        createdIn:
          destination: rental.reservationCreated
          group: inventory_command_service_group

        carReservedAtLocationOut:
          destination: rental.carReservedAtLocation

axon:
  kafka:
    client-id: inventory-command-service
    default-topic: rental.inventoryEvent

    producer:
      bootstrap-servers: localhost:9091
