server:
  port: 9082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

spring:
  h2:
    console:
      path: /h2
      enabled: true

  jpa:
    show-sql: true

axon:
  kafka:
    client-id: inventory-query-service
    default-topic: rental.inventoryEvent

    consumer:
      bootstrap-servers: localhost:9091
      group-id: inventory_query_service_group
      event-processor-mode: TRACKING
